### ISSUE TITLE
When I enter:  /* what variables are in sashelp.baseball */, and ask to generate code, I get a blank box below the question and no errors.

### ISSUE THREAD

**Issue by lchelwig82** [sassoftware/sas-copilot#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. PC or Mac]
 - Version: [e.g. 0.0.2, you can find the version number by clicking the extension icon] 

**Reporter's Organization**

**Additional context**

**Comment by 2TomLi** [comment]
Fixed, no empty response will be returned.
