### ISSUE TITLE
Generate SAS Code problem

### ISSUE THREAD

**Issue by cdoninger** [sassoftware/sas-copilot#11]
**Describe the bug**
I entered this line
/* print sashelp.cars */
and when I selected generate code it inserted the next line number and showed the dialog to accept 1 of 1 line but it did not generate the proc print.   It didn't generate anything.  This seems like a bug

Adding that when I highlight the comment and choose comment, then I get the code generated.

**To Reproduce**

**Expected behavior**
I expected to see 
proc print data=sashelp.cars; run;

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. PC or Mac]
 - Version: [e.g. 0.0.2, you can find the version number by clicking the extension icon] 
 - PC

**Reporter's Organization**
AAT

**Additional context**

**Comment by 2TomLi** [comment]
Fixed, no empty response will be returned.
