### ISSUE TITLE
Content is lost in 'Send Feedback' tab

### ISSUE THREAD

**Issue by qyanggit** [sassoftware/sas-copilot#14]
**Describe the bug**
There is an issue with 'Send feedback' tab. When I switch to another tab in VScode, I lost everything I typed in the 'Send Feedback' tab. Is this a VScode issue or Copilot 'Send feedback' control issue?

**Expected behavior**
The content would still be there before I click the Submit' button.

**Reporter's Organization**
SAS Institute

**Comment by ouhanyou** [comment]
This has been fixed in version 0.0.4
