### ISSUE TITLE
Add keyboard shortcuts for comment/explain/generate

### ISSUE THREAD

**Issue by Criptic** [sassoftware/sas-copilot#2]
**Is your feature request related to a problem? Please describe.**
As a user I would like to avoid having to use my mouse to interact with the three core capabilities comment/explain/generate.

**Describe the solution you'd like**
Adding keyboard shortcuts that can trigger the actions would be ideal

**Describe alternatives you've considered**
Continue using Shift+F10 (brings up the context menu in VS Code on Windows) and then using the arrow keys to navigate to the desired action.

**Additional context**
None

**Reporter's Organization**
SAS

**Comment by RalphJMarshall** [comment]
This is an accessibility violation (inability to use the product with only a keyboard), so I'd argue it's a bug rather than an enhancement. (SAS Employee here)

**Comment by ouhanyou** [comment]
Hi @RalphJMarshall, as @Criptic mentioned above in the **alternatives** section, keyboard users can use keyboard shortcut (Shift+F10) and arrow keys to execute the three commands. So I'm keeping this issue as an enhancement. Let me know if I miss anything, thanks!

**Comment by ouhanyou** [comment]
I did some Googling on how VSCode handles this. I found this feature request https://github.com/Microsoft/vscode/issues/41579 and its fix https://github.com/microsoft/vscode/pull/91232.

So users can already set their own keyboard shortcuts to execute the CodeLens:
<img width="1049" alt="image" src="https://github.com/sassoftware/sas-copilot/assets/105657176/e326a79d-4905-4837-befc-5158cb5f4b44">

I'm closing this one out with these findings. But feel free to re-open if this solution doesn't work well for you. Thanks for opening this issue! @Criptic
