### ISSUE TITLE
chat tab can display identical responses to generate code request

### ISSUE THREAD

**Issue by bepede** [sassoftware/sas-copilot#20]
**Describe the bug**
If multiple identical responses are provided to a generate code request, the suggestion toolbar provides one.  However, the conversation pane will display both solutions.  This duplication creates unnecessary clutter in the chat pane.

**To Reproduce**
1. Paste `/* print 10 observations from sashelp.cars */`
2. Generate code
3. Observe the toolbar and the chat pane.

**Expected behavior**
If suggestions are identical, only provide one in the chat pane.

**Screenshots**
![image](https://github.com/sassoftware/sas-copilot/assets/165972009/29042944-8859-4304-8a61-e3246debe868)

**Desktop (please complete the following information):**
 - OS: PC, VSCode 1.85.2
 - Version: 0.0.2

**Reporter's Organization**
R&D

**Comment by ouhanyou** [comment]
Thanks for opening the bug @bepede !
This issue has been fixed in version 0.0.4. So closing this one out.
