### ISSUE TITLE
Generated code is inserted at wrong location if cursor is moved while code generation is in progress

### ISSUE THREAD

**Issue by falkoschulz** [sassoftware/sas-copilot#22]
**Describe the bug**
Dependent on your internet speed or complexity of the code to be generated, the actual code generation can take a few seconds or longer. If the user moves the cursor to a different location within the SAS file, the generated code is inserted at the current cursor position instead of the one originally initiated from. 

**To Reproduce**
1. Enter a comment with instruction and select generate code
2. While code generation is in progress, move the cursor to a different location within your program. Maybe even put the cursor in a middle of another code segment, to make the issue more obvious.
3. Note, that the new generated code is inserted at the new location, instead the original one the request got initiated from

**Expected behavior**
I would expect the code to be generated next to the comment with related instructions. Given this async request, we should take the original cursor position into account when inserting the generated code.

**Screenshots**
![Code_De7nHl8sJN](https://github.com/sassoftware/sas-copilot/assets/39793507/24f375a0-9ef5-4e53-8b1b-ca193d9d66e4)

**Desktop (please complete the following information):**
 - OS: [PC
 - Version: 0.0.2

**Reporter's Organization**
Platform Services

**Comment by ouhanyou** [comment]
This issue has been fixed in 0.0.3
