### ISSUE TITLE
Background of chat window is the same color as editor background in SAS Dark and SAS Light themes

### ISSUE THREAD

**Issue by bepede** [sassoftware/sas-copilot#51]
**Describe the bug**
The background of the chat window is the same color is the same as the editor background when using the SAS Dark or SAS Light themes.  When the chat window is empty, it can be hard to see what is supposed to be where.  Most other extensions that I have seen using a side pane like this use a different color background than the default for the editor. In high contrast, they have the same background, but there is a clear line separating the different panes.  Once you start using the chat feature, a scroll bar will start to appear to create a separation.

**To Reproduce**
Make sure the chat window is empty to really notice.

**Expected behavior**
As mentioned, most other extensions use a different color background for the side pane, including the SAS VSCode extension.  

**Screenshots**
![image](https://github.com/sassoftware/sas-copilot/assets/165972009/ed79a666-22c2-47f7-a6be-eef015de5ca7)

**Desktop (please complete the following information):**
 - OS: Windows, VSCode 1.85.2
 - Version: 0.0.3 

**Reporter's Organization**

R&D

**Additional context**

**Comment by ouhanyou** [comment]
Thanks for opening this bug @bepede!
This issue has been fixed in version 0.0.4
