### ISSUE TITLE
Code generate happening in wrong place

### ISSUE THREAD

**Issue by Brycicles** [sassoftware/sas-copilot#56]
**Describe the bug**
Generated code will be pasted where the cursor is. Might be considered a bug if its supposed to be pasted underneath the comment used to generate the code.

**To Reproduce**
1. Go to a /* comment with promts */
2. Click on generate code.
3. Scroll down to move cursor (with arrow keys or click on some other line with the mouse)
4. generated code will always appear under cursor not under the relevant comment. 

**Expected behavior**
I would expect it to retain the line the prompt was given on. Otherwise if a user clicks somewhere while waiting for copilot to generate it might end up breaking code.

**Screenshots**
![GenCodeInWrongPlace](https://github.com/sassoftware/sas-copilot/assets/45973059/d539e94f-5a8f-42af-ba53-49dafca4aeb6)

**Desktop (please complete the following information):**
 - OS: Windows PC
 - Version: 0.0.2

**Reporter's Organization**

**Additional context**

**Comment by 2TomLi** [comment]
Already fixed in the V0.0.3 version
